### ISSUE TITLE
Error During Testing

### ISSUE THREAD

**Issue by JohnSeals** [Arnaud73/ngx-matomo#13]
I'm running ngx-matomo 0.1.2 using Angular CLI: 7.3.6, Node: 10.13.0, and Angular: 7.2.9. It works great but on only one of my tests (using "ng test"). Every other component test passes just fine. This one test only always fails with this error:
`TypeError: Cannot read property 'push' of undefined
    at MatomoTracker.push../node_modules/ngx-matomo/ngx-matomo.es5.js.MatomoTracker.setDocumentTitle (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-matomo/ngx-matomo.es5.js:701:1)
    at new ApiDetailComponent (http://localhost:9876/_karma_webpack_/webpack:/src/app/api-detail/api-detail.component.ts:30:24)
    at createClass (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:22159:1)
    at createDirectiveInstance (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:22028:1)
    at createViewNodes (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:23254:1)
    at createRootView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:23168:1)
    at callWithDebugContext (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:24176:1)
    at Object.debugCreateRootView [as createRootView] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:23686:1)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:21507:1)
    at initComponent (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/testing.js:1916:1)
`

The app builds ok andruns fine. It's just the test that fails. My test is very simple"
`it('should create', () => {
    expect(component).toBeTruthy();
  });`

Any ideas?

**Comment by Arnaud73** [comment]
I guess the Tracker is not injected in your test configuration, resulting in the global _paq object of Matomo not being available, then failing on setDocumentTitle.

**Comment by JohnSeals** [comment]
Thanks for the very quick response! I thought that might be he case but I have imported Matomo Module: 
`import { MatomoModule } from 'ngx-matomo';`
and added it to the imports:
`beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ ApiDetailComponent ],
      imports: [
        HttpClientTestingModule,
        RouterTestingModule,
        AppRoutingModule,
        ScrollingModule,
        MessagesModule,
        MessageModule,
        FormsModule,
        DialogModule,
        MatomoModule,
        MatIconModule],
      providers: [
        Title,
        Dialog,
        AlertService
      ],
    })`

Its' weird. I have like 7 other components all using the plug-in and they work great! it's only this one. And like I said itbuildsfine and every other test passes.

A head scratcher . .  .

**Comment by Arnaud73** [comment]
You indeed included the module, but in your case, there is no call to the `init`method of the `MatomoInjector` which has the responsability to inject the real Matomo tracker in the page. This call creates the global `_paq` object for Matomo.
In you case, when your component call setDocumentTitle, it fails since `_paq` does not exist.

2 solutions:
* Get the MatomoInjector inject the Matomo tracker
* Create a dummy `_paq` before running the test: `window._paq = window._paq || [];`

**Comment by JohnSeals** [comment]
Thanks so much for your quick reply and assistance!

**Comment by cwalker67** [comment]
@JohnSeals - would you mind posting an example of how you solved this error.  I'm having the same problem but can't seem to get the fix right.

Thanks

**Comment by JohnSeals** [comment]
I’ll have to try and find the code! Be glad to post it when I track it down. 😀

**Comment by 164424-RoshanKanwal** [comment]
@Arnaud73  
Can you elaborate the solutions. Even I am facing the same issue.
![image](https://user-images.githubusercontent.com/44638941/96970472-5f37b800-1531-11eb-8c21-3efd83a02e70.png)

**Comment by dana-c0914** [comment]
We had this issue with storybook storyshots.

For us it worked to add `window._paq = window._paq || [];` in one of the stories file, write before the export.
