### ISSUE TITLE
Enable routerTracking will throw error

### ISSUE THREAD

**Issue by retondong** [Arnaud73/ngx-matomo#65]
Below is error message:
`Unhandled Promise rejection: R3InjectorError(AppModule)[MatomoModule -> MatomoRouteTracker -> Router -> Router -> Router]: NullInjectorError: No provider for Router! ; Zone: <root> ; Task: Promise.then ; Value: NullInjectorError: R3InjectorError(AppModule)[MatomoModule -> MatomoRouteTracker -> Router -> Router -> Router]: NullInjectorError: No provider for Router! at NullInjector.get (core.js:11100) at R3Injector.get (core.js:11267) at R3Injector.get (core.js:11267) at R3Injector.get (core.js:11267) at injectInjectorOnly (core.js:4751) at Module.ɵɵinject (core.js:4755) at Object.MatomoRouteTracker_Factory [as factory] (ngx-matomo.js:1919) at R3Injector.hydrate (core.js:11437) at R3Injector.get (core.js:11256) at new MatomoModule (ngx-matomo.js:1961) NullInjectorError: R3InjectorError(AppModule)[MatomoModule -> MatomoRouteTracker -> Router -> Router -> Router]: NullInjectorError: No provider for Router! at NullInjector.get (http://localhost:4200/vendor.js:27658:27) at R3Injector.get (http://localhost:4200/vendor.js:27825:33) at R3Injector.get (http://localhost:4200/vendor.js:27825:33) at R3Injector.get (http://localhost:4200/vendor.js:27825:33) at injectInjectorOnly (http://localhost:4200/vendor.js:21309:33) at Module.ɵɵinject (http://localhost:4200/vendor.js:21313:61) at Object.MatomoRouteTracker_Factory [as factory] (http://localhost:4200/vendor.js:233002:308) at R3Injector.hydrate (http://localhost:4200/vendor.js:27995:35) at R3Injector.get (http://localhost:4200/vendor.js:27814:33) at new MatomoModule (http://localhost:4200/vendor.js:233044:27)`
Use npm install is ok for me but use yarn install will throw this error

**Comment by reisi007** [comment]
Same problem with Angular 11 and 1.0.0-rc.0 -> yarn install fails but npm install works as well!
